### ISSUE TITLE
mobile front-end bubbles aren't visible at the bottom of the page.

### ISSUE THREAD

**Issue by sebastienvg** [pimatic/pimatic#533] opened 2015-02-10 16:17 UTC
I am unable to see the content of the bubbles or click their content (the graph link for example) when the devices are located at the bottom of the page. Is there a way to have these bubbles appear inline instead of under the mouse when you hover it?

**Comment by sweetpi** [comment] 2015-02-12 07:01
Thanks for reporting. That's a known bug in the mobile-frontend, it will hopefully be fixed soon.

**Comment by sweetpi** [comment] 2015-02-12 08:09
Oh duplicate of #465.

**Closed by sweetpi** 2015-02-12 08:09 UTC
Labels: bug
