### ISSUE TITLE
Error in Pimatic-Ultrasonic

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#1074] opened 2017-06-25 08:18 UTC
Hello,

I'm getting this error:

error [pimatic]: please call `usonic.init()` first
09:55:46error [pimatic-ultrasonic,Ultrasonic]: Error restoring changed device ultrasonic: please call `usonic.init()` first

**Comment by mwittig** [comment] 2017-09-15 10:46
As the issue is with Pimatic-Ultrasonic which is separate project I am closing this ticket now. Please use the following tickt for fcorrespondence: 

https://github.com/wutu/pimatic-ultrasonic/issues/6

**Closed by mwittig** 2017-09-15 10:46 UTC
