### ISSUE TITLE
pulling data from sparkfun phant

### ISSUE THREAD

**Issue by chrigui** [pimatic/pimatic#847] opened 2016-03-31 08:17 UTC
is it possible to pull data from a phant data stream ?

sample stream: https://data.sparkfun.com/streams/dZ4EVmE8yGCRGx5XRX1W
Data Export methods: Json, CSV, Mysql, PostgeSQL, ATOM

is there a way to pull data using the mentioned methods please ?

thank you.

**Comment by mwittig** [comment] 2016-03-31 09:47
You can pull the data in desired format, e.g, JSON using curl or wget and do some script-based post processing, e.g., extract the most recent data record using something like https://github.com/trentm/json. Then, you can push data into pimatic by setting up variables in pimatic which will be set using the pimatic REST API. There are couple of example how to do this, which can be found on Pimatic Forum.

**Comment by chrigui** [comment] 2016-03-31 09:49
@mwittig Thanks Marcus i will look in to it and report back if it worked. :)

**Comment by sweetpi** [comment] 2016-04-07 06:10
I'm closing this issue here, because its more a general question not a bug report please continue in the forum.

**Closed by sweetpi** 2016-04-07 06:10 UTC
