### ISSUE TITLE
public webserver

### ISSUE THREAD

**Issue by hg-smart** [pimatic/pimatic#951] opened 2016-07-21 07:15 UTC
There are always troubles running a webserver locally and then open the server for the internet... Is it possible to host pimatic on a public webserver and then simply push messages from "local rasperries" to that webserver ?

What are the requirements for this public websever, when not running pimatic on a raspberry ?
node.js of course, what else ?

**Comment by sweetpi** [comment] 2016-07-30 12:36
You can run pimatic on any hardware that supports Node.js. However you can't use all plugins and there is currently no simple way to push events from the raspberry pi to a remote server.

pimatic is best suited to run on your local raspberry pi or other arm device. If you want the webinterface to be accessible from the internet you can open the port and forward it to the raspberry pi in the config of your router (check the manual). However make sure that you are using only SSL and you have a strong password. 

I'm closing this here, because that's not a bug report. If you have further questions please ask in the forum.

**Closed by sweetpi** 2016-07-30 12:36 UTC
