### ISSUE TITLE
[v0.9] Shell execute error

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#829] opened 2016-03-20 21:49 UTC
```Error: Cannot read property 'length' of undefined``` when executing an command from rule.

**Comment by sweetpi** [comment] 2016-03-20 22:32
Which version of pimatic-shell-execute? Is there no stack trace?

**Comment by sweebee** [comment] 2016-03-20 22:46
latest version 0.8.18.

```
22:45:03.415 [pimatic-shell-execute] error: [ShellActionHandler] Error: Cannot read property 'length' of undefined
22:45:03.431 [pimatic] error: rule wake-phones error executing an action: undefined
22:45:03.436 [pimatic] debug: undefined
22:45:03.441 [pimatic] error: Error on evaluation of rule condition of rule wake-phones: undefined
22:45:03.444 [pimatic] debug: Error: Cannot read property 'length' of undefined
22:45:03.521 [pimatic-shell-execute] error: [ShellActionHandler] Error: Cannot read property 'length' of undefined
22:45:03.527 [pimatic] error: rule wake-phones error executing an action: undefined
22:45:03.530 [pimatic] debug: undefined
22:45:03.609 [pimatic-shell-execute] error: [ShellActionHandler] Error: Cannot read property 'length' of undefined
22:45:03.618 [pimatic] error: rule wake-phones error executing an action: undefined
22:45:03.640 [pimatic] debug: undefined
22:45:03.693 [pimatic-shell-execute] error: [ShellActionHandler] Error: Cannot read property 'length' of undefined
22:45:03.702 [pimatic] error: rule wake-phones error executing an action: undefined
22:45:03.706 [pimatic] debug: undefined
22:45:03.719 [pimatic-shell-execute] error: [ShellActionHandler] Error: Cannot read property 'length' of undefined
22:45:03.723 [pimatic] error: rule wake-phones error executing an action: undefined
22:45:03.726 [pimatic] debug: undefined
```

**Comment by mwittig** [comment] 2016-03-21 00:15
Same error here. It worked fine with the snapshot it took last Thursday.

**Comment by sweebee** [comment] 2016-03-21 23:11
And i get very high CPU usage with this plugin enabled.

**Comment by sweetpi** [comment] 2016-03-22 06:58
I'm think this is an effect resulting of other errors. Couldn't reproduce the issue with the other two rule bugs fixed. @sweebee Could you retest?

**Comment by sweebee** [comment] 2016-03-22 07:57
Still no luck. Also reinstalled shell execute. (still wants pimatic < 0.9 btw)

**Comment by sweebee** [comment] 2016-03-22 08:01
Different error btw:
```
03error [pimatic]: rule wake-phones error executing an action: undefined
09:00:03error [pimatic]: rule wake-phones error executing an action: undefined
09:00:03error [pimatic]: rule wake-phones error executing an action: undefined
09:00:03error [pimatic]: rule wake-phones error executing an action: undefined
09:00:03error [pimatic]: Error on evaluation of rule condition of rule wake-phones: undefined
```

**Comment by sweebee** [comment] 2016-03-22 09:21
Found out it executes fine.

**Comment by sweetpi** [comment] 2016-03-26 08:47
It should be fully fixed now (https://github.com/pimatic/pimatic-shell-execute/commit/2b94eded82e747e0e9f638ebb7dcdbd95cf82bc8).

**Closed by sweetpi** 2016-03-26 08:47 UTC
Labels: v0.9 beta testing
