### ISSUE TITLE
Homeduino Analog Dimmer

### ISSUE THREAD

**Issue by Oxx90** [pimatic/pimatic#1026] opened 2016-12-01 11:52 UTC
Hello, 
sorry for my bad english...

if i set the pwm level of an Arduino pin with pimatic the voltage is 0,7v @100%.
but when i send (AW 10 255) to the arduino via serialpython the voltage is 100% of VCC.

have anyone the same problem?

THX

**Comment by mwittig** [comment] 2016-12-20 13:27
Hi, 
I think this is a duplicate of https://github.com/pimatic/pimatic-homeduino/issues/73
Fixture is in progress.

**Closed by mwittig** 2016-12-20 13:27 UTC
Labels: duplicate
