### ISSUE TITLE
[forum] I do not see the text if I in the forum something about my iphone poste

### ISSUE THREAD

**Issue by cm86** [pimatic/pimatic#984] opened 2016-09-30 22:08 UTC
Reopened
https://github.com/pimatic/pimatic/issues/961

Iphone 6s with iOS 10.0.2

Because it's not solved

**Comment by leader21** [comment] 2016-09-30 22:35
the issue is known at nodebb. maybe the upcomming version 1.2 will solve it. otherwise we will check for another solution if there is any...

**Comment by mwittig** [comment] 2016-10-03 21:13
https://forum.pimatic.org/topic/2280/forum-update-to-v1-2-composer-zen-mode/2

Closing this now

**Closed by mwittig** 2016-10-03 21:13 UTC
