### ISSUE TITLE
[pimatic-location] iphone-finder:  SyntaxError: Unexpected end of input at Object.parse (native) 

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#730] opened 2015-10-23 07:06 UTC
hey, i get the following error since i have installed the pimatic-location plugin in combination with iphone.

```
error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) 
at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 
at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) 
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16 
at process._tickDomainCallback (node.js:459:13) 
This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment] 2015-10-23 08:47
Looks like a incomplete request. Does it happen periodically? Maybe @Oitzu has an idea.

**Comment by Oitzu** [comment] 2015-10-23 08:56
@p4co86 Hard to say, but guessing on the code, the cause could be a bad login.
The module doesn't handle that correctly.

**Comment by p4co86** [comment] 2015-10-23 09:23
this is what i get now:

```
error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
11:06:12error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
10:49:28error [pimatic-shell-execute]:
10:48:11error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
10:43:11error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
10:42:11error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by Yves911** [comment] 2015-10-24 06:14
@p4co86 on my side i still use the module and everything is working smoothly...

**Comment by p4co86** [comment] 2015-11-04 17:26
I still get the error. Any ideas?

error [pimatic]: A uncaught exception occured: SyntaxError: Unexpected end of input at Object.parse (native) at /root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:26:31 at IncomingMessage.<anonymous> (/root/pimatic-app/node_modules/pimatic-location/node_modules/iphone-finder/lib/iphone-finder.js:42:48) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickDomainCallback (node.js:459:13) This is most probably a bug in pimatic or in a module, please report it!

**Comment by sweetpi** [comment] 2015-11-05 06:49
I can't do very much about it, because I don't own a ios device.

**Comment by p4co86** [comment] 2015-11-05 15:02
ok, sometimes i get this error for a few hours, then there are gone.

```
error [pimatic-location]: Didn't received correct Gmaps-Api response!
```
i have no api set in the config.

**Comment by Oitzu** [comment] 2015-11-05 15:14
The gmaps-api is used to calculate distances. You are probably exceeding the maximum calls to the api and need to use an api-key or an lower update-interval.

**Comment by p4co86** [comment] 2015-11-05 15:15
ah ok. thanks for that where can i set the interval on iphone?

**Comment by p4co86** [comment] 2015-12-10 20:43
i noticed that the error comes periodicaly.
from 23:56-03:00 sometimes 00:03-03:05 
i dont wont to create another api account if not nessecary. 
so the error should be gone when i set the interval from 1 minute to 3 minute?
thanks

**Comment by Oitzu** [comment] 2015-12-10 22:00
Well. Give it a try. Another reason could be 24 hour DSL disconnect?

**Comment by mwittig** [comment] 2016-10-27 17:20
Closing this one now. Please re-open if you wish to follow-up.

**Closed by mwittig** 2016-10-27 17:20 UTC
