### ISSUE TITLE
homeduino not in receive mode automatically when installed

### ISSUE THREAD

**Issue by Huehnerbrust** [pimatic/pimatic#1016] opened 2016-11-22 22:24 UTC
Hi!

I had the problem that I could not receive anything with homeduino on a fresh install, while I saw RF data in the screen terminal.

It took me some days to find out that I had to add options to the config.json for homeduino:

      "enableReceiving": true,
      "debug": true

This should be standard or at least included in the guide on how to install the homeduino.

**Comment by leader21** [comment] 2016-11-22 22:44
just checked the config scheme. it is set as default !! see for yourself. 
https://github.com/pimatic/pimatic-homeduino/blob/master/homeduino-config-schema.coffee#L37-L40

**Comment by mwittig** [comment] 2016-11-25 11:22
@Huehnerbrust I am closing this now as I am not able to reproduce the problem. Please re-open the ticket if you're able to reproduce it. Please provide further details in case.

**Closed by mwittig** 2016-11-25 11:22 UTC
