### ISSUE TITLE
Telegram Plugin stops receiving

### ISSUE THREAD

**Issue by tees54** [pimatic/pimatic#1132] opened 2019-10-06 19:56 UTC
I have some rules, that sends status messages with telegram. These rules always works well.
Additional i have some rules, which gets triggered when a telegram messages is received. But after some days these rules does ot trigger and telegram does not ask for the passphrase. After a restart of pimatic, these messages gets delivered and the plugin sends the messages to telegram.

Does anybody know this behaivor and found a solution or the cause of the problem?

Kind regards

**Comment by SenTzu01** [comment] 2019-10-28 22:49
This issue is likely caused by your ISP changing the external IP address of your internet connection as confirmed by other users on the Pimatic forum. Will not be fixed in the Telegram plugin. Please close this issue as it is not Pimatic Core related.

**Closed** 2019-10-29 07:44 UTC
