### ISSUE TITLE
[pimatic] bug in getting state in rule

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#1095] opened 2018-04-06 12:07 UTC
I had this issue several times. Don't know if its my fault or pimatic's fault.

A plugin has a device with a state variable. In the config the device has the name ```Test Device``` and the id ```test-device```.

This works in a rule:
```
when state of Test Sensor = "value" then ...
```

this doesn't:
```
when state of test-sensor = "value" then...
```

The rule with the device id does not trigger.

this is the code for the device like this (removed most of unrelevant data):
```
class RaspBeeSwitchSensor extends env.devices.Device

    constructor: (@config,lastState) ->
      @id = @config.id
      @name = @config.name
      @deviceID = @config.deviceID
      @_state = lastState?.state?.value
      super(@config,lastState)

      myRaspBeePlugin.on "event", (data) =>
        if data.id is @deviceID and data.type is "sensors"
          @_updateAttributes data

      @getInfos()
      myRaspBeePlugin.on "ready", () =>
        @getInfos()

    _updateAttributes: (data) ->
      console.log(data)
      if data.state?.buttonevent?
        @_setState(data.state.buttonevent.toString())

    getInfos: ->
      if (myRaspBeePlugin.ready)
        myRaspBeePlugin.Connector.getSensor(@deviceID).then (res) =>
          @_updateAttributes res

    destroy: ->
      super()

    attributes:
      state:
        description: "State of the sensor",
        type: t.string

    _setState: (value) ->
      if @_state is value then return
      @_state = value
      @emit 'state', value

    getState: -> Promise.resolve(@_state)
```

**Comment by sweebee** [comment] 2018-04-06 21:27
For now its just a basic sensor that shows the button state, so we can use all the buttons there are for deconz/raspbee. 

it outputs raw states like:

1002 = single click
1004 = double click
2002 = button 2 single click

**Comment by sweebee** [comment] 2018-04-10 21:29
Seems to only occur if checking for a state which is a string. If it’s a Boolean everything works fine. 

Have you already looked into it? It’s quite annoying

**Comment by mwittig** [comment] 2018-04-20 17:11
Thanks for the info on button states. I haven't looked into the issue yet. Will setup a test config this and try to reproduce it.

**Comment by sweebee** [comment] 2018-05-25 13:32
Have you already looked into it?

**Comment by mwittig** [comment] 2018-05-28 09:18
Yes, Works for me. I have tested it with the following mockup code which is close to that code of the `RaspBeeSwitchSensor`device class you posted:

```
  class RBeeSwitchSensor extends Device

    constructor: (@config,lastState) ->
      @id = @config.id
      @name = @config.name
      @deviceID = @config.deviceID
      @_state = lastState?.state?.value ? "foo"
      super(@config,lastState)
      min = 0
      max = 4
      vals = ["foo", "bar", "blo", "bla", "blubb"]
      setInterval( () =>
        @_setState(vals[Math.floor(Math.random() * (max - min + 1)) + min])
      , 500)

    _updateAttributes: (data) ->
      console.log(data)
      if data.state?.buttonevent?
        @_setState(data.state.buttonevent.toString())

    destroy: ->
      super()

    attributes:
      state:
        description: "State of the sensor",
        type: t.string

    _setState: (value) ->
      if @_state is value then return
      @_state = value
      @emit 'state', value

    getState: -> Promise.resolve(@_state)
```

Maybe there is an issue with the logic of the `_updateAttributes` method. Did you trace the variable value in the Variables view, i.e., does the variable change to the expected value?

**Comment by mwittig** [comment] 2018-06-04 00:13
Closing this for now. Please re-open if you wish to follow-up

**Closed by mwittig** 2018-06-04 00:13 UTC
