### ISSUE TITLE
pimatic-ping and sleeping iDevices

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#209] opened 2014-08-07 17:02 UTC
Shortly (about 30 seconds) after an iPhone or iPad goes to sleep it does no longer answer ping packets because the hardware handeling this is going to sleep/powersave. This means the iDevice can't be detected by the plugin anymore and thus is set to "not present" which is wrong.

However it seems that the lowlevel networking is still up and running and the "sleeping" iDevice answwers for example syn-requests.

See:
http://www.power-home.com/forum/forum_posts.asp?TID=3250&PN=0&TPN=1

If someone has some time it would be great if we could integrate something like that into the plugin.

If I find some time I will also try to do it.

**Comment by georg90** [comment] 2015-01-31 22:53
I feeld the need for this to be more stable :-)
I got a nice door contact and want to extent my automation now with my phone.

I found a little thing called ```bonjour dns service```
So this will listen on Port 5353 UDP for connections.
I tested it myself a couple of times and it always wakes up the iphone and keeps it awake for ~25-30sec!

Here's the code with hping:
```sudo hping3 -2 -p 5353 192.168.0.33```

**Comment by Xento** [comment] 2015-02-01 02:05
Does this decrease the batterylife much?
Because at the moment the iPhone awakes automatically every 15 minutes. 
So i made a rule that sets a variable to false when the iphone wasn't detected for 20 minutes and another rule that sets it to true when the iphone is present.

**Comment by georg90** [comment] 2015-02-01 07:09
Every 15min? I need to check this on my phone..
I had the check on the whole night, battery is at 98%..don't think that it makes a big difference

**Comment by StavrosVon** [comment] 2015-03-10 09:29
Could anyone confirm that either of these methods works with an IPhone 6?

I have confirmed that both the above work with IPhone 4s, but am having difficulties getting either of them to work with IPhone6.

**Comment by Yves911** [comment] 2015-03-10 10:27
My script described here https://github.com/pimatic/pimatic/issues/209#issuecomment-51710184 do not work anymore properly with my iphone 5s (was working perfectly fine with an iphone 4).
now i am using
```
IF PingIphone is absent for 30 minutes THEN set $SomeOneAtHome := 0
```
but it's not a perfect solution (it will need 30 minutes to detect that there is nobody home)

**Comment by StavrosVon** [comment] 2015-03-10 10:31
@Yves911  you should try @georg90 method shown above this works for me on a 4S very reliably.

Can I ask if your phones have been enabled for WIFI sync with ITunes? This is the only difference between the 4S and the 6 I can identify (besides the fact they are different phones :) )

**Comment by Yves911** [comment] 2015-03-10 10:39
@StavrosVon what i don't understand here https://github.com/pimatic/pimatic/issues/209#issuecomment-72341081 is : do i have to install or enable something on the iphone side?

About your question, yes i tried to enable WIFI sync with ITunes but it doesn't work (and i don't know why) on my iphone 5s (was also working fine with iphone 4)

**Comment by StavrosVon** [comment] 2015-03-10 10:43
@Yves911 nothing to install on the IPhone, sending the UDP requests simply causes the IPhone to wake up and reconnect to the wifi so you can then ping it normally.

You will not get a response from the UDP requests either.

For my 4S it works like this:

sudo hping3 -2 -c 3 -p 5353 MYIPHONE
sudo ping MYIPHONE

If the IPhone is in the house this will cause it to wakeup and the the normal ping will work.

Did you enabled WIFI sync before you tried to tcpping your phone?

**Comment by Yves911** [comment] 2015-03-10 12:24
thanks @StavrosVon i will try this evening
about
> Did you enabled WIFI sync before you tried to tcpping your phone?

Yes (because port 62078 relates to WIFI sync)

**Comment by Yves911** [comment] 2015-03-10 18:04
@StavrosVon solution from @georg90 works very nicely (better than my solution with the script).
So now i have in the cron
```
*/2 * * * * /usr/sbin/hping3 -2 -c 3 -p 5353 192.168.1.49  >> /dev/null  2>&1
```
and then same rule in pimatic than before but with a shorter delay
```
IF PingIphone is absent for 5 minutes THEN set $SomeOneAtHome := 0
```
Thanks guys

**Comment by georg90** [comment] 2015-03-10 18:12
@Yves911 Can you monitor your battery usage? Every 2min prevents the iphone completely from sleeping I guess, so that would be very interesting..

**Comment by Yves911** [comment] 2015-03-10 18:52
@georg90 yes i will but not before this weekend (phone will be with me @work until friday)

**Comment by Xento** [comment] 2015-04-06 12:55
Do you have any results?

**Comment by Yves911** [comment] 2015-04-06 17:01
Oops I forgot this thread, afters few weeks I can say that I don't see any problem with the battery usage

**Comment by sweetpi** [comment] 2015-04-12 08:52
Moving all Feature request to the forum, so closing this.

**Closed** 2015-04-12 08:56 UTC
Labels: enhancement

**Comment by quintz** [comment] 2016-04-26 10:37
@Yves911 

Can I copy the cron entry just like that? Or do I have to adjust smth? (except the IP of course.. ;-) )
