### ISSUE TITLE
locale.de not translating on/off for switch state

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#969] opened 2016-08-25 21:12 UTC
check the forum. 
the switch state remains in english and wont be translatet. for me it seems tje locale.de is ok so far
https://forum.pimatic.org/topic/2155/german-locale-isn-t-working/

**Comment by SLiX69** [comment] 2016-08-28 20:27
as mentioned in the forum, this is duplicate of #787

**Comment by mwittig** [comment] 2016-08-28 21:33
duplicate

**Closed by mwittig** 2016-08-28 21:33 UTC
