### ISSUE TITLE
"Oops... No connection" after saving enabled/disabled rule

### ISSUE THREAD

**Issue by WasVerzachter** [pimatic/pimatic#1058] opened 2017-03-08 22:36 UTC
When I try to enable or disable a rule and then click on save, I get a pop-up saying "Oops... No connection".
Any idea where to look?
Pimatic version 0.9.38
Plugins:
cron 0.8.8 loaded activated
homeduino 0.9.11 loaded activated
mail 0.8.6 loaded activated
mobile-frontend 0.9.11 loaded activated
mqtt 0.9.5 loaded activated
openweather 0.9.4 loaded activated
shell-execute 0.9.8 loaded activated
smartmeter2 0.0.18 loaded activated
sunrise 0.8.7 loaded activated

Pi:
ls -l config.json 
-rw-r--r-- 1 pi pi 37898 Mar  8 23:00 config.json

**Comment by mwittig** [comment] 2017-03-08 22:39
Pls check the log file `pimatic-daemon.log` located in the installation directory and post error messages you may find

**Comment by WasVerzachter** [comment] 2017-03-09 08:35
Hereby my pimatic-daemon.log
I've cleaned it up by removing my location and also rule logging.
I did a realtime test: tail -f pimatic-daemon.log  and then disabling the rule; no entry pimatic-daemon.log
Thanks,
Erik


19:39:39.574 2017-03-07 Tuesday
19:39:47.985 [pimatic] info: Starting pimatic version 0.9.38
19:39:52.457 [pimatic, ppm] info: 2.15.11
19:39:52.534 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.8)
19:39:53.360 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.9.11)
19:39:54.493 [pimatic] info: Loading plugin: "pimatic-shell-execute" (0.9.8)
19:39:54.560 [pimatic] info: Loading plugin: "pimatic-homeduino" (0.9.11)
19:39:55.642 [pimatic] info: Loading plugin: "pimatic-openweather" (0.9.4)
19:39:55.751 [pimatic] info: Loading plugin: "pimatic-sunrise" (0.8.7)
19:39:55.806 [pimatic] info: Loading plugin: "pimatic-mail" (0.8.6)
19:39:56.812 [pimatic] info: Loading plugin: "pimatic-mqtt" (0.9.5)
19:39:57.939 [pimatic] info: Loading plugin: "pimatic-smartmeter2" (0.0.18)
19:39:57.978 [pimatic-cron] info: the time is: Tue Mar 07 2017 19:39:57 GMT+0100 (CET)
19:39:59.288 [pimatic-sunrise] info: Your location is set to ***Removed for privacy***
19:39:59.447 [pimatic-mqtt] debug: Registering device class MqttSwitch
serialport options 
{ portName: '/dev/ttyUSBsmartmeter',
  baudRate: 115200,
  dataBits: 8,
  parity: 'none',
  stopBits: 1,
  flowControl: false }
19:40:00.404 [pimatic] info: New device "Smartmeter"...
19:40:00.410 [pimatic] warn: The device type Smartmeterdevice2 does not implement a destroy function
19:40:00.511 [pimatic] info: New device "Totaal Electriciteit"...
19:40:00.550 [pimatic] info: New device "Totaal Gas"...
19:40:00.578 [pimatic] info: New device "Actueel Electriciteit"...
19:40:00.613 [pimatic] info: New device "Electriciteit Dag Verbruik"...
19:40:00.649 [pimatic] info: New device "Electriciteit Uur Verbruik"...
19:40:00.686 [pimatic] info: New device "Gas Dag Verbruik"...
19:40:00.725 [pimatic] info: New device "Gas Uur Verbruik"...
19:40:00.788 [pimatic] info: New device "Electriciteit Dag Kosten"...
19:40:00.837 [pimatic] info: New device "Electriciteit Uur Kosten"...
19:40:00.874 [pimatic] info: New device "Gas Dag Kosten"...
19:40:00.901 [pimatic] info: New device "Gas Uur Kosten"...
19:40:00.981 [pimatic] info: New device "evoHome"...
19:40:01.062 [pimatic] info: New device "Zonsopgang"...
19:40:01.141 [pimatic] info: New device "Zonsondergang"...
19:40:01.284 [pimatic] info: New device "Huidig weer Reuver"...
19:40:01.375 [pimatic] info: New device "Weersvoorspelling Reuver - morgen"...
19:40:01.526 [pimatic] info: New device "System Memory Usage"...
19:40:01.612 [pimatic] info: New device "System Disk Usage"...
19:40:01.677 [pimatic] info: New device "System CPU Temperature"...
19:40:01.739 [pimatic] info: New device "Woonkamer Temperature"...
19:40:01.797 [pimatic] info: New device "Keuken Temperature"...
19:40:01.881 [pimatic] info: New device "Achterkamer Temperature"...
19:40:02.172 [pimatic] info: New device "WC Temperature"...
19:40:02.244 [pimatic] info: New device "Woonkamer Temp Setpoint"...
19:40:02.319 [pimatic] info: New device "Keuken Temp Setpoint"...
19:40:02.403 [pimatic] info: New device "Achterkamer Temp Setpoint"...
19:40:02.681 [pimatic] info: New device "WC Temp Setpoint"...
19:40:02.738 [pimatic] info: New device "Buiten Achterdeurlamp"...
19:40:02.798 [pimatic] info: New device "Woonkamer voor hanglamp"...
19:40:02.850 [pimatic] info: New device "Woonkamer achter hanglamp"...
19:40:02.903 [pimatic] info: New device "Achterkamer Lichtrail"...
19:40:02.988 [pimatic] info: New device "Buiten Achterrolluik"...
19:40:03.035 [pimatic] info: New device "Buiten Voordeurlamp"...
19:40:03.077 [pimatic] info: New device "Woonkamer Schemerlamp"...
19:40:03.118 [pimatic] info: New device "Keuken Close-in boiler"...
19:40:03.171 [pimatic] info: New device "Reserve"...
19:40:03.211 [pimatic] info: New device "Achterkamer Sta Lamp"...
19:40:03.253 [pimatic] info: New device "Achterkamer Computer Lamp"...
19:40:03.293 [pimatic] info: New device "Achterkamer Kerstboom"...
19:40:03.339 [pimatic] info: New device "Zolder Trap"...
19:40:03.371 [pimatic] info: New device "Achterkamer Schuifpui"...
19:40:03.400 [pimatic] info: New device "Zolder CV ketel"...
19:40:03.435 [pimatic] info: New device "Zolder Lichtsensor"...
19:40:03.470 [pimatic] info: New device "Woonkamer voor Temperatuur"...
19:40:03.502 [pimatic] info: New device "Woonkamer voor luchtvochtigheid"...
19:40:03.532 [pimatic] info: New device "Woonkamer voor Luchtdruk"...
19:40:03.567 [pimatic] info: New device "Achterkamer Temperatuur"...
19:40:03.610 [pimatic] info: New device "Achterkamer luchtvochtigheid"...
19:40:03.660 [pimatic] info: New device "Achterkamer Luchtdruk"...
19:40:03.695 [pimatic] info: New device "Woonkamer piano Temperatuur"...
19:40:03.723 [pimatic] info: New device "Woonkamer piano luchtvochtigheid"...
19:40:03.753 [pimatic] info: New device "Woonkamer piano Luchtdruk"...
- Serial port is open
19:40:16.938 [pimatic-mqtt] info: Successfully connected to MQTT Broker default
19:40:17.990 [pimatic-mobile-frontend] info: packing static assets
19:40:18.865 [pimatic-mobile-frontend] info: packing static assets finished
19:40:18.881 [pimatic-mobile-frontend] info: rendering html
19:40:34.392 [pimatic-mobile-frontend] info: rendering html finished
19:40:34.586 [pimatic] info: Listening for HTTPS-request on port 443...
19:40:34.590 [pimatic] info: Listening for HTTP-request on port 80...
19:40:35.638 [pimatic-homeduino] info: Connected to homeduino device.

**Comment by mwittig** [comment] 2017-03-09 12:12
Thanks, I can't find anything suspicious here. There are no errors logged.
Questions:
- Which browser do you use?
- Does the "Oops... No connection" toast appear all times when saving a rule or does it only happen sporadically?
- Do you use http or https to connect to pimatic? Both listeners have been setup, but possibly there is a problem with the  https setup

**Comment by WasVerzachter** [comment] 2017-03-09 21:04
I tried Firefox (Ubuntu & Win10), IE11, Chrome and Edge.
http gives the error message, however https works well.
How about that ?

**Comment by mwittig** [comment] 2017-03-14 21:54
> http gives the error message, however https works well.

Ok, interesting. I'll try to reproduce that. Please use "https" as work-around or disable "https" if youu don't need it

**Comment by mwittig** [comment] 2018-01-05 11:03
I am still not able to reproduce this problem and I am closing this ticket now as there has been no follow-up since a couple of months. Please re-open if you are still seeing this problem. In case, please provide an example on how to reproduce the problem. Thanks

**Closed by mwittig** 2018-01-05 11:03 UTC
