### ISSUE TITLE
vhduino - High CPU usage since the last update

### ISSUE THREAD

**Issue by yaba** [pimatic/pimatic#1077] opened 2017-07-05 21:26 UTC
I've updated yesterday to the latest version.
After reboot, process vhduino is always using CPU at 90% (and more)
Thanks.

**Comment by mwittig** [comment] 2017-07-05 21:31
What do you mean by last update? Did you update your Raspbian OS?

**Comment by yaba** [comment] 2017-07-05 21:38
Yes, both Raspbian and Pimatic.

**Comment by mwittig** [comment] 2017-07-05 21:54
Closing this one. Please use https://github.com/pimatic/virtualhomeduino/issues/3 for further correspondence. Thanks

**Closed by mwittig** 2017-07-05 21:54 UTC

**Comment by mwittig** [comment] 2017-07-05 23:05
> Yes, both Raspbian and Pimatic.

Ok, thanks. The issue is caused by the new kernel.
